account/urls.py
from django.urls import path
from django.contrib.auth import logout
from . import views


urlpatterns = [
    path("my_account/", views.my_account, name="my_account"),
    path("signup/", views.signup, name="signup"),
    path("signin/", views.signin, name="signin"),
    path("signout/", views.signout, name="signout"),
    path("my_favorites/", views.my_favorites, name="my_favorites"),
    path("save/", views.save, name="save"),
    path("mail_save/", views.mail_save, name="mail_save"),
    path("delete/", views.delete, name="delete"),
]

app_name = "account"

catalog/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("search/", views.search, name="search"),
    path("<int:product_id>/", views.detail, name="detail"),
    path("legal/", views.legal, name="legal"),
]

app_name = "catalog"

catalog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField("Nom", max_length=75, unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField("Nom", max_length=200)
    brand = models.CharField("Marque", max_length=200)
    code = models.CharField("Code barre", max_length=13)
    nutriscore = models.CharField("Nutriscore", max_length=1)
    description = models.TextField("Description", blank=True, null=True)
    categories = models.ManyToManyField(Category, related_name="Catégories", blank=True)
    picture = models.URLField()
    url = models.URLField()

catalog/views.py
""" Catalog's views module.
Every app view is called here.
"""

#- Django Modules
from django.shortcuts import render, get_object_or_404

#- Custom modules
from .models import Product


def index(request):
    """
    Index page view.
    """
    context = {}
    return render(request, "catalog/index.html", context)

def search(request):
    """
    Search bar view.
    """
    query = request.GET.get("query")
    if not query:
        products = Product.objects.all()
    else:
        products = Product.objects.filter(name__icontains=query)

        if not products.exists():
            products = Product.objects.filter(code__icontains=query)

    title = 'Résultats pour la recherche "{}":'.format(query)
    context = {"products": products, "query": query, "title": title}
    return render(request, "catalog/search.html", context)


def detail(request, product_id):
    """
    Product's detail view.
    """
    product = get_object_or_404(Product, pk=product_id)
    categories = " ".join(
        [category.name for category in product.categories.all()]
        )
    context = {
        "product_name": product.name,
        "nutriscore": product.nutriscore,
        "description": product.description,
        "brand": product.brand,
        "thumbnail": product.picture,
        "url": product.url,
        "categories":categories,
    }

    return render(request, "catalog/detail.html", context)


def legal(request):
    """
    Legal page view.
    """
    context = {}
    return render(request, "catalog/legal.html", context)

catalog/templates/catalog/detail.html
{% extends 'catalog/base.html' %}

{% block content %}
{% load static %}
<div id="detail">
  <hr>
  <h1 id="productHeader" class="intro-text text-center py-5" style="background-image: url('{{ thumbnail }}');">{{ product_name }}</h1>
  <hr class="detail-separator">
  <div class="row" style="margin-bottom:50px;">
    <div style="text-align: center;" class="col-md-6">
      <img src="{{ thumbnail }}" alt="{{ product_name }}" class="img-responsive mx-auto d-block"">
      <div style="margin-bottom:45px">
        <h2 class="text-center">Catégories</h2>
        {%for category in categories%}
          <p style="text-align: center;">{{category}}</p>
        {% endfor %}
      </div>
    </div>
    <div class="col-md-6">
      <div style="margin-bottom:45px">
       <h2 class="text-center">Informations</h2>
        <ul style="list-style:none;">
          <li><span style="font-weight:bold;">Marque:</span> {{brand}}</li>
          <li id="nutriscore">{{nutriscore}}</li>
          <li><span style="font-weight:bold;">Description:</span> {{ description }}</li>
          <li><a href="{{url}}">Plus d'informations sur OpenFoodFacts</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<script>
  var e = document.getElementById("nutriscore")
switch (e.innerHTML){
        case 'A':
            e.innerHTML = e.innerHTML.replace('A',"<img src=\"{% static 'catalog/img/nutriscore-A.png' %}\" alt='Nutricore A'>");
             break;
        case 'B':
        e.innerHTML = e.innerHTML.replace('B',"<img src=\"{% static 'catalog/img/nutriscore-B.png' %}\" alt='Nutricore B'>");

             break;
        case 'C':
        e.innerHTML = e.innerHTML.replace('C',"<img src=\"{% static 'catalog/img/nutriscore-C.png' %}\" alt='Nutricore C'>");
             break;
        case 'D':
        e.innerHTML = e.innerHTML.replace('D',"<img src=\"{% static 'catalog/img/nutriscore-D.png' %}\" alt='Nutricore D'>");
             break;
        default:
          e.innerHTML = e.innerHTML.replace('E',"<img src=\"{% static 'catalog/img/nutriscore-E.png' %}\" alt='Nutricore E'>");
          break;
    }
</script>
{% endblock %}

catalog/templates/catalog/index.html
{%extends 'catalog/base.html' %}

{% block content %}
<!-- Masthead-->
<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-12 align-self-end">
                <h1 class="text-uppercase text-white font-weight-bold">Du gras, oui, mais de qualité !</h1>
                <hr class="divider my-4" />
            </div>
            <div id="search-zone" class="col-lg-12 align-self-baseline">
                <h2 class="text-white-75 font-weight-light mb-5">Trouvez un produit de substitution pour ceux que vous consommez tous les jours.</h2>
                <p class="align-center" style="width:50%;">{%include 'catalog/search_form.html' %}</p>
            </div>
        </div>
    </div>
</header>
<!-- About-->
<section class="page-section bg-primary" id="about">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12">
            <h2 class="text-center">Colette & Rémy :</h2>
            <hr class="divider my-4" />
            <p>Pur Beurre est l'initiative de deux amoureux de la gastronomie française, Colette Tatou et Rémy, que vous avez déjà certainement rencontrés dans notre excellent restaurant Ratatouille.</p>
                Colette Tatou : <blockquote>"Nous aimons tous manger, surtout en France ! Personnellement, une baguette fraîche, du bon fromage de chèvre et un bon vin rouge me suffisent amplement. Comme tout le monde, je fais mes courses au supermarché. Mais petit à petit je me suis rendue compte, surtout lorsque nous avons ouvert le restaurant, que je pouvais remplacer les produits aseptisés que j'avais l'habitude d'acheter par de bons produits du terroir Et souvent pour le même prix !"</blockquote>
                Remy : <blockquote>"Pour ma part je me rendais déjà dans bien des magasins car j'aime beaucoup me balader, surtout dans les caves et les cuisines. Je connaissais par coeur le contenu des boutiques bio (dont je raffole) ainsi que les ingrédients de tous les aliments vendus. Lorsque Colette m'a demandé si elle pouvait remplacer son Nutella matinal par un aliment plus sain, je savais tout de suite où le trouver. L'idée de Pur Beurre était née !"</blockquote>
            </div>
        </div>
        <div class="row justify-content-center">
            {% load static %}
            <div class="col-lg-6 col-sm-12 text-center">
                <img src="{% static 'catalog/img/colette.png' %}" alt="Colette Tatou">
            </div>
            <div class="col-lg-6 col-sm-12 text-center">
                <img src="{% static 'catalog/img/ratatouille.png' %}" alt="Remy" style="width:100%">
            </div>
        </div>
    </div>
</section>
<!-- Contact-->
<section class="page-section" id="contact">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="mt-0">Contactez-nous !</h2>
                <hr class="divider my-4" />
                <p class="text-muted mb-5">Des suggestions ? Une demande particulière ? N'hésitez pas ! Nous serons ravi de vous accueillir !</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
                <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
                <div>+33 0 00 00 00 00</div>
            </div>
            <div class="col-lg-4 mr-auto text-center">
                <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
                <!-- Make sure to change the email address in BOTH the anchor text and the link target below!-->
                <a class="d-block" href="mailto:biscuit@purbeurre.miam">biscuit@purbeurre.miam</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

catalog/templates/catalog/legal.html
{%extends 'catalog/base.html' %}

{% block content %}

<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-12 align-self-center">
                <h1 class="text-uppercase text-white font-weight-bold">Mentions Légales</h1>
                <p class="text-white text-capitalize">Ce site a été développé et déployé par Thomas Hintermeier-Saive dans le cadre du Projet 8 de la formation "Développeur d'Application Python" d'Open Classrooms, et selon les critères établis dans la <a href="https://company-82435.frontify.com/d/6Yy9WFJdtp8j/pur-beurre-style-guide">charte graphique</a>.</p>
            </div>
        </div>
    </div>
</header>

<section class="page-section" id="copyrights">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
            <h2 class="text-center">Crédit photo :</h2>
            <hr class="divider my-4" />
            <p>
            <ul>
                <li><a href='https://unsplash.com/photos/eqsEZNCm4-c'>Olenka Kotyk</a></li>
                <li><a href='https://unsplash.com/photos/k60JspcBwKE'>Kawin Harasai</a></li>
                <li><a href="https://unsplash.com/photos/YTbFHT9_IhY">Greg Janneau</a></li>
            </ul>
        </p>
        <p>

        </p>
            </div>
            <div class="col-md-6">
                <h2 class="text-center">Copyright :</h2>
                <p>
                    Toutes les images de Colette et Rémy, les vidéo et autre éléments tirés du film d'Animation <em>Ratatouille</em> sont la propriété de Walt Disney Company et sont soumis aux droits d'auteur.
                </p>
                <video width="320" height="240" controls>
                    {% load static %}
                    <source src="{% static 'catalog/res/ratatouille-vf-bande-annonce.mp4' %}" type="video/mp4">
                  Votre navigateur ne peut pas lire cette vidéo !
                  </video>  
            </div>
        </div>
    </div>
</section>

<section class="page-section" id="theme">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12text-center">
                <h2 class="mt-0">Thèmes et icônes</h2>
                <hr class="divider my-4" />
                <p class="text-muted mb-5">Le thème du site est basé sur le template Bootstrap disonible à <a href="https://startbootstrap.com/theme/creative">cette adresse</a>.<br>
                Les icônes de connexion, et déconnexion sont issues de <a href="https://fontawesome.com/v4.7.0/icons/">Font Awesome</a>, tandis que l'icône de Carotte est issue de <a href="https://thenounproject.com/term/carrot/29691/">The Noun Project</a></p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

catalog/templates/catalog/list.html
<div style="margin-top:70px;" class="col-lg-12 py-5 my-5" id="masthead">
    <hr>
    <h2 class="intro-text text-center">{{ list_title }}</h2>
    <hr class="detail-separator">
</div>

{% include 'catalog/search_form.html' %}

{% if products|length_is:"0" %}
    <div class="text-center">
        Nous n'avons pas pu trouver le produit demandé. Ré-essayez !
    </div>
    {% load static %}
{% else %}
    {% for product in products %}
    <div style="margin-top:20px;" class="col-sm-4 text-center">
        <a href="{% url 'catalog:detail' product_id=product.id %}">
                <img class="thumbnail mx-auto d-block" src="{{ product.picture }}" alt="{{ product.name }}"></a>
                <div class="nutriscoreIcon">{{product.nutriscore}}</div>
            <p class="py-2 p_name">{{ product.name }}</p>
            {% if user.is_authenticated %}
                {% csrf_token %}
                <span class="iconify" data-icon="fa-floppy-o" data-inline="false"></span>
                <button id='{{product.id}}' onclick="save(this.id, &quot;{%url 'account:save' %}&quot;)">Sauvegarder</button>
            </form>
            {% endif %}
        </div>
    </div>
    {% if forloop.counter|divisibleby:3 %} <div class="clearfix"></div>{% endif %}
    {% endfor %}
<div class="clearfix"></div>

{% endif %}
<script>
    var nutriscore = document.getElementsByClassName('nutriscoreIcon');
var e;
for (e of nutriscore) {
    switch (e.innerHTML){
        case 'A':
            e.innerHTML = e.innerHTML.replace('A',"<img src=\"{% static 'catalog/img/nutriscore-A.png' %}\" alt='Nutricore A'>");
             break;
        case 'B':
        e.innerHTML = e.innerHTML.replace('B',"<img src=\"{% static 'catalog/img/nutriscore-B.png' %}\" alt='Nutricore B'>");

             break;
        case 'C':
        e.innerHTML = e.innerHTML.replace('C',"<img src=\"{% static 'catalog/img/nutriscore-C.png' %}\" alt='Nutricore C'>");
             break;
        case 'D':
        e.innerHTML = e.innerHTML.replace('D',"<img src=\"{% static 'catalog/img/nutriscore-D.png' %}\" alt='Nutricore D'>");
             break;
        default:
          e.innerHTML = e.innerHTML.replace('E',"<img src=\"{% static 'catalog/img/nutriscore-E.png' %}\" alt='Nutricore E'>");
          break;
    }
}
</script>

catalog/templates/catalog/results.html
{% extends 'catalog/base.html' %}

{% block content %}

    {% include 'catalog/list.html' with list_title='Résultat de votre recherche' %}

{% endblock %}

catalog/templates/catalog/search.html
{% extends 'catalog/base.html' %}

{% block content %}

    {% include 'catalog/list.html' with list_title=title %}

{% endblock %}

catalog/templates/catalog/search_form.html
<div class="detail-separator">
    <form id="search-form" class="col-md-6 col-md-offset-3 text-center" action="{% url 'catalog:search' %}" method="get" accept-charset="utf-8">
      <div class="form-group">
        <label for="searchForm"></label>
        <input id="searchForm" class="form-control" name="query" placeholder="Trouvez un produit par nom, code barre...">
      </div>
    </form>
</div>